sonar.projectKey=JUAN20031102_CALIDAD
sonar.organization=juan20031102
sonar.projectName=CALIDAD
sonar.projectVersion=1.0

# Define la ruta a analizar (el punto . indica todo el proyecto)
sonar.sources=.

sonar.sourceEncoding=UTF-8
